# Generated by Django 5.0.1 on 2024-02-07 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='emailinfo',
            name='info_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
